<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account settings updated successfully' => 'แก้ไขการตั้งค่าเสร็จเรียบร้อย',
    'Avatar Base Url' => '',
    'Avatar Path' => '',
    'Password updated successfully' => 'เปลี่ยนรหัสผ่านเสร็จเรียบร้อย',
    'Profile updated successfully' => 'แก้ไขบัญชีส่วนตัวเสร็จเรียบร้อย',
    'About' => 'เกี่ยวกับ',
    'Account' => 'บัญชี',
    'Account ({username})' => 'บัญชี ({username})',
    'Account Settings' => 'ตั้งค่าบัญชี',
    'Change password' => 'เปลี่ยนรหัสผ่าน',
    'Confirm New Password' => 'ยืนยันรหัสผ่านใหม่อีกครั้ง',
    'Confirm Password' => 'ยืนยันรหัสผ่าน',
    'Contact' => 'ติดต่อ',
    'Email' => 'อีเมล์',
    'Firstname' => 'ชื่อ',
    'Gender' => 'เพศ',
    'Home' => 'หน้าหลัก',
    'Language' => 'ภาษา',
    'Lastname' => 'นามสกุล',
    'Locale' => 'ภาษา',
    'Login' => 'เข้าสู่ระบบ',
    'Logout ({username})' => 'ออกจากระบบ ({username})',
    'New Password' => 'รหัสผ่านใหม่',
    'Old Password' => 'รหัสผ่านเดิม',
    'Password' => 'รหัสผ่าน',
    'Profile' => 'ข้อมูลผู้ใช้งาน',
    'Profile picture' => 'รูปถ่าย',
    'Settings' => 'ตั้งค่า',
    'Signup' => 'ลงทะเบียน',
    'Title' => 'คำนำหน้า',
    'Update' => 'แก้ไข',
    'Update Password' => 'เปลี่ยนรหัสผ่าน',
    'Update Profile' => 'แก้ไขข้อมูลส่วนตัว',
    'User ID' => 'รหัสผู้ใช้งาน',
    'Username' => 'ชื่อผู้ใช้งาน',
    'Website' => 'เว็บไซต์',
];
